"use client";

import "./globals.css";
import { Lato } from "next/font/google";
import { Layouts } from "@/commons/layouts/index";
import { ThemeProvider } from "next-themes";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={lato.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Layouts>{children}</Layouts>
        </ThemeProvider>
      </body>
    </html>
  );
}
